/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#006194",
        "primary-container": "#007bb9",
        "primary-fixed": "#cce5ff",
        "primary-fixed-dim": "#93ccff",
        secondary: "#565e74",
        "secondary-container": "#dae2fd",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        tertiary: "#00685f",
        "tertiary-container": "#008378",
        "tertiary-fixed": "#89f5e7",
        "tertiary-fixed-dim": "#6bd8cb",
        surface: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "surface-container-high": "#dce9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "on-primary": "#ffffff",
        "on-primary-container": "#fdfcff",
        "on-primary-fixed": "#001d31",
        "on-primary-fixed-variant": "#004b73",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f4fffc",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#005049",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#3f4850",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#93ccff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#707881",
        "outline-variant": "#bfc7d2",
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        gutter: "1.25rem",
        margin: "2rem",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
